name: Metrics
on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: gtsvetanov
          template: classic
          base: activity, repositories
          config_timezone: Europe/Sofia
          plugin_languages: yes
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
          plugin_languages_threshold: 0.2%